version: "3.3"
services:
  cron:
    build: "./"
    volumes:
      - "./cron.d:/etc/cron.d"
      - "../../scripts/clear_chat:/bin/clear_chat"
      - "../../scripts/check_user_authorization:/bin/check_user_authorization"
      - "../../creds:/creds"
      - "./entrypoint.sh:/entrypoint.sh"
    environment:
      - "CHAT_NAME=${CHAT_NAME}"
    command: ["/bin/bash", "/entrypoint.sh", "/creds/creds.json", "$CHAT_NAME"]
