version: "3.3"
services:
  bot:
    build: "./"
    volumes:
      - "../../scripts/clear_bot:/bin/clear_bot"
      - "../../scripts/check_user_authorization:/bin/check_user_authorization"
      - "../../creds:/creds"
      - "./entrypoint.sh:/entrypoint.sh"
    command: ["/bin/bash", "/entrypoint.sh", "/creds/creds.json"]
